apteryx_insert("/policy-based-routing/rules/*/rule-id",nil,nil)
apteryx_insert("/policy-based-routing/rules/*/application",nil,nil)
apteryx_insert("/policy-based-routing/rules/*/from",nil,nil)
apteryx_insert("/policy-based-routing/rules/*/to",nil,"any")
apteryx_insert("/policy-based-routing/rules/*/nexthop",nil,nil)
apteryx_insert("/policy-based-routing/settings/enable",{["disable"]="0",["enable"]="1"},"0")
apteryx_insert("/policy-based-routing/settings/debug-enable",{["disable"]="0",["enable"]="1"},"0")
